Sprint 17
AndreyOvchinnikovDev/Tracker pull request #4
Opened 2023-09-25 13:59 UTC by AndreyOvchinnikovDev

Очень тяжелый спринт
Здравствуй ревьюер, заранее спасибо

2023-09-26 08:23 UTC, protos17 requested changes

2023-09-26 08:23 UTC, protos17 commented on Tracker/Domain/AnalyticsService.swift
> +        }
При работе со словарями можно использовать такое заполнение:

        params["event"] = event.rawValue
        params["screen"] = screen.rawValue
        item.map { params["item"] = $0.rawValue }
        
        если есть опциональное значение, мы его можем прогнать через map и если оно есть, то установится значением для соответствуеюще ключа, если его не будет, ничего не установится, это еще и сократить повторение кода при проверке, потому что может оказаться много опциональных полей и их всех тогда не придется проверять как у тебя

2023-09-26 08:23 UTC, protos17 commented on Tracker/TrackList/TrackListViewController.swift
> +        view.backgroundColor = .ypWhite
Необходимо убрать, потому что в addSubviews() у тебя устанавливается цвет фона

2023-09-26 08:23 UTC, protos17 commented on Tracker/Category/CategoryViewModel.swift
> +                if category.name == "Закрепленые" { continue } else {
Сравнения со строкой лучше заменить сравнением с кейсом энама

2023-09-26 08:23 UTC, protos17 commented on Tracker/Category/CategoryViewModel.swift
>          trackerCategories = try! categoryStore.fetchTrackerCategories()
Рекомендую принудительные try не использовать

2023-09-26 08:23 UTC, protos17 commented on Tracker/Domain/TrackerCategoryStore.swift
> +        let fixedCategory = TrackerCategory(name: "Закрепленые", trackers: addTrackers(trackersCoreData: fixedTrackers))
Рекомендую сделать энам с двумя кейсами - один зарепленный, второй нет и сравнивать через этот энам

2023-09-26 08:23 UTC, protos17 commented on Tracker/Domain/TrackerStore.swift
> +        var catTrackers = category.first?.trackers?.allObjects as! [TrackerCoreData]
Метод указан как throws, поэтому можно избавиться от forceCast и выбросить ошибку - throw

2023-09-26 08:23 UTC, protos17 commented on Tracker/TrackList/TrackListViewControllerCell.swift
>      private let plusButton: UIButton = {
Чтобы xcode не ругался, необходимо указать как lazy var

2023-09-26 12:53 UTC, AndreyOvchinnikovDev commented on Tracker/Domain/AnalyticsService.swift
> +        }
что осилил поправил, спасибо за полезные советы 🙂

2023-09-27 07:21 UTC, protos17 approved these changes

2023-09-27 07:21 UTC, protos17 commented on Tracker/Domain/TrackerStore.swift
> +        var catTrackers = category.first?.trackers?.allObjects as [TrackerCoreData]
Здесь чтобы не ругался xcode, рекомендую заменить на:

var catTrackers = category.first?.trackers?.allObjects.compactMap { $0 as? TrackerCoreData } ?? []

2023-09-27 07:21 UTC, protos17 commented on Tracker/Category/NewCategoryViewController.swift
> +    lazy private var addCategoryButton: UIButton = {
Принято указывать как private lazy var

2023-09-27 14:44 UTC, merged